name: restore-cache-template
on:
  schedule:
    - cron: '*/5 * * * 1'
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:
jobs:
  restore-cache:
    if: github.event.schedule != ''
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        r: ['release']
        r-repo: ['https://packagemanager.rstudio.com/all/__linux__/focal/latest']
    steps:
      - name: Set restore key partials
        run: |
          Rscript -e 'cat("OS_VERSION=", sessionInfo()$running, sep = "")' >> $GITHUB_ENV
          Rscript -e 'cat("R_VERSION=", R.Version()$version.string, sep = "")' >> $GITHUB_ENV
          echo 'WORKFLOW=${{ github.workflow }}' >> $GITHUB_ENV
          echo 'TMPDIR=${{ runner.temp }}' >> $GITHUB_ENV
      - name: Restore GHA Cache
        uses: ktmud/cached-dependencies@064315d61e424e60d440fa77e8afda19cdd7211a
        with:
          parallel: true
          run: |
            cache-restore renv
            cache-restore knitr
  rmarkdown:
    if: github.event.schedule == ''
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        r: ['release']
        r-repo: ['https://packagemanager.rstudio.com/all/__linux__/focal/latest']
    # Only runs PR jobs concurrently & uses same group as other ghpages jobs
    # PR jobs run in their own branch & do not deploy anything - so we assume they can run concurrently
    concurrency:
      group: ghpages-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_REPOS_OVERRIDE: ${{ matrix.r-repo }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - uses: prncevince/r-actions/setup-renv@main
        with:
          type: 'restore'
          cache-version: 
      - uses: prncevince/r-actions/setup-knitr-cache@main
        with:
          cache: 'knitr-cache_cache'
          cache-hash: 'knitr-cache.Rmd'
      - name: Build site
        run: Rscript build.R
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./docs
          target-folder: .